### ISSUE TITLE
[FIX] 소스코드 전체적으로 리팩토링

### ISSUE THREAD

**Issue by guswlsakfls** [guswlsakfls/hae-library-management-system#31]
# Description
모든 테스트 코드 점검 및 추가, 불필요한 코드/파일 정리, 비효율적인 소스코드 리팩토링

## Todo
- [x] 테스트 코드 점검
- [x] 테스트 코드 추가
- [x] 불필요한 코드/파일 정리
- [x] 주석 달기
- [x] 비효율적인 코드 수정
