### ISSUE TITLE
[FIX] 서류들 정리

### ISSUE THREAD

**Issue by guswlsakfls** [guswlsakfls/hae-library-management-system#33]
# Description
지금까지 작성한 서류 정리

## Todo
- [x] 요구사항정의서
- [x] 아키텍처설계서
- [x] 화면설계서
- [x] 테이블정의서
- [x] 물리모델ERD(엔티티도 같이 수정)
- [x] 통합테스트 시나리오/케이스
- [x] 단위테스트 시나리오/케이스
- [x] 완료 보고서(ppt)
